export type CityId =
  | "default"
  | "rome"
  | "barcelona"
  | "berlin"
  | "copenhagen"
  | "bari"
  | "london"
  | "paris"
  | "amsterdam"
  | "lisbon"
  | "dublin"
  | "prague"
  | "bologna"
  | "pag"
  | "athens"
  | "warsaw"
  | "budapest"
  | "zagreb"
  | "brussels"
  | "vienna";

export type MotionStyle = "settle" | "coastal-drift" | "slow-push" | "still-water" | "sea-breeze" | "global-orbit";

export interface CityMedia {
  id: CityId;
  city: string;
  country: string;
  sceneTitle: string;
  cityStory: string;
  character: string;
  pulse: string;
  videoSrc: string;
  imageSrc: string;
  overlayGradient: string;
  colorGrade: string;
  focalPoint: string;
  motionStyle: MotionStyle;
  palette: {
    backgroundFrom: string;
    backgroundMiddle: string;
    backgroundTo: string;
    ambientGlow: string;
    accentGlow: string;
    shadow: string;
  };
  ambientParticles: {
    count: number;
    speed: number;
    label: string;
  };
  mediaDescriptor: string;
}

export const CITY_MEDIA: Record<CityId, CityMedia> = {
  default: {
    id: "default",
    city: "Global",
    country: "Connected scenes",
    sceneTitle: "Global creative network",
    cityStory: "Aerial night routes connecting creative cities across a shared horizon.",
    character: "Warm global pulse",
    pulse: "46 active signals",
    videoSrc: "/media/cities/global.mp4",
    imageSrc: "/media/cities/global.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(8, 6, 14, 0.22) 0%, rgba(8, 6, 14, 0.48) 44%, rgba(6, 5, 12, 0.92) 100%)",
    colorGrade: "saturate(0.90) contrast(1.05) brightness(0.60)",
    focalPoint: "50% 42%",
    motionStyle: "global-orbit",
    palette: {
      backgroundFrom: "#08070D",
      backgroundMiddle: "#0F0D1A",
      backgroundTo: "#08070D",
      ambientGlow: "#6C4FD4",
      accentGlow: "#C8F000",
      shadow: "#08070D",
    },
    ambientParticles: { count: 19, speed: 0.16, label: "Connected signals" },
    mediaDescriptor: "Aerial city network / night",
  },
  rome: {
    id: "rome",
    city: "Rome",
    country: "Italy",
    sceneTitle: "Rome creative map",
    cityStory: "A warm aerial arrival above historic rooftops, stone landmarks and evening movement.",
    character: "Historic warm cinematic",
    pulse: "34 cultural movements",
    videoSrc: "/media/cities/rome.mp4",
    imageSrc: "/media/cities/rome.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(10, 6, 8, 0.20) 0%, rgba(10, 6, 8, 0.44) 42%, rgba(6, 5, 12, 0.90) 100%)",
    colorGrade: "saturate(1.00) contrast(1.10) brightness(0.65)",
    focalPoint: "52% 38%",
    motionStyle: "settle",
    palette: {
      backgroundFrom: "#0A0810",
      backgroundMiddle: "#110D1E",
      backgroundTo: "#08070D",
      ambientGlow: "#6C4FD4",
      accentGlow: "#FF3D7F",
      shadow: "#08070D",
    },
    ambientParticles: { count: 16, speed: 0.11, label: "Evening light" },
    mediaDescriptor: "Historic aerial / golden hour",
  },
  barcelona: {
    id: "barcelona",
    city: "Barcelona",
    country: "Spain",
    sceneTitle: "Barcelona coastal scene",
    cityStory: "The coastline and lit urban grid meeting after sunset, alive with Mediterranean color.",
    character: "Mediterranean nightlife",
    pulse: "28 signals after sunset",
    videoSrc: "/media/cities/barcelona.mp4",
    imageSrc: "/media/cities/barcelona.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(12, 6, 10, 0.18) 0%, rgba(12, 6, 10, 0.40) 40%, rgba(6, 5, 12, 0.88) 100%)",
    colorGrade: "saturate(1.10) contrast(1.08) brightness(0.70)",
    focalPoint: "52% 47%",
    motionStyle: "coastal-drift",
    palette: {
      backgroundFrom: "#0C0814",
      backgroundMiddle: "#140F22",
      backgroundTo: "#08070D",
      ambientGlow: "#9B7FFF",
      accentGlow: "#FF3D7F",
      shadow: "#08070D",
    },
    ambientParticles: { count: 22, speed: 0.2, label: "Night coast lights" },
    mediaDescriptor: "Coastal aerial / nightlife",
  },
  berlin: {
    id: "berlin",
    city: "Berlin",
    country: "Germany",
    sceneTitle: "Berlin warehouse pulse",
    cityStory: "An industrial night approach across dense roofs, warehouse corridors and low light.",
    character: "Industrial underground",
    pulse: "19 late-room signals",
    videoSrc: "/media/cities/berlin.mp4",
    imageSrc: "/media/cities/berlin.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(4, 5, 10, 0.30) 0%, rgba(4, 5, 10, 0.55) 44%, rgba(4, 4, 8, 0.94) 100%)",
    colorGrade: "saturate(0.62) contrast(1.22) brightness(0.52)",
    focalPoint: "48% 43%",
    motionStyle: "slow-push",
    palette: {
      backgroundFrom: "#080710",
      backgroundMiddle: "#0E0C1C",
      backgroundTo: "#06050C",
      ambientGlow: "#5A3EC8",
      accentGlow: "#C8F000",
      shadow: "#06050C",
    },
    ambientParticles: { count: 11, speed: 0.09, label: "Low light haze" },
    mediaDescriptor: "Industrial aerial / night",
  },
  copenhagen: {
    id: "copenhagen",
    city: "Copenhagen",
    country: "Denmark",
    sceneTitle: "Copenhagen waterline",
    cityStory: "A quiet aerial glide across waterfront architecture, cool air and reflected light.",
    character: "Nordic minimal cold",
    pulse: "14 precise signals",
    videoSrc: "/media/cities/copenhagen.mp4",
    imageSrc: "/media/cities/copenhagen.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(5, 8, 14, 0.24) 0%, rgba(5, 8, 14, 0.46) 44%, rgba(4, 6, 12, 0.90) 100%)",
    colorGrade: "saturate(0.82) contrast(1.10) brightness(0.64)",
    focalPoint: "50% 50%",
    motionStyle: "still-water",
    palette: {
      backgroundFrom: "#080C14",
      backgroundMiddle: "#0D1220",
      backgroundTo: "#06080F",
      ambientGlow: "#4ABFB0",
      accentGlow: "#9B7FFF",
      shadow: "#06080F",
    },
    ambientParticles: { count: 9, speed: 0.07, label: "Water lights" },
    mediaDescriptor: "Waterfront aerial / blue hour",
  },
  bari: {
    id: "bari",
    city: "Bari",
    country: "Italy",
    sceneTitle: "Bari sea-front night",
    cityStory: "A southern night settling above limestone roofs and the Adriatic harbor edge.",
    character: "Southern coastal warmth",
    pulse: "17 harbor-side signals",
    videoSrc: "/media/cities/bari.mp4",
    imageSrc: "/media/cities/bari.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(8, 6, 10, 0.20) 0%, rgba(8, 6, 10, 0.43) 42%, rgba(6, 5, 12, 0.88) 100%)",
    colorGrade: "saturate(1.04) contrast(1.10) brightness(0.67)",
    focalPoint: "53% 49%",
    motionStyle: "sea-breeze",
    palette: {
      backgroundFrom: "#0A0810",
      backgroundMiddle: "#12101E",
      backgroundTo: "#08070D",
      ambientGlow: "#7B5CF0",
      accentGlow: "#00D4B4",
      shadow: "#08070D",
    },
    ambientParticles: { count: 17, speed: 0.13, label: "Harbor air" },
    mediaDescriptor: "Sea-front aerial / warm night",
  },
  london: {
    id: "london",
    city: "London",
    country: "United Kingdom",
    sceneTitle: "London night frequency",
    cityStory: "A grey aerial drift above rooftop terraces, canal bridges and shifting fog layers.",
    character: "Industrial fog cinematic",
    pulse: "31 late signals",
    videoSrc: "/media/cities/london.mp4",
    imageSrc: "/media/cities/london.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(6, 7, 12, 0.28) 0%, rgba(6, 7, 12, 0.52) 44%, rgba(5, 6, 10, 0.92) 100%)",
    colorGrade: "saturate(0.68) contrast(1.18) brightness(0.58)",
    focalPoint: "50% 40%",
    motionStyle: "slow-push",
    palette: {
      backgroundFrom: "#0C0E14",
      backgroundMiddle: "#111520",
      backgroundTo: "#07090E",
      ambientGlow: "#7B8FA8",
      accentGlow: "#9B7FFF",
      shadow: "#060810",
    },
    ambientParticles: { count: 13, speed: 0.10, label: "Fog signals" },
    mediaDescriptor: "Aerial rooftop / night fog",
  },
  paris: {
    id: "paris",
    city: "Paris",
    country: "France",
    sceneTitle: "Paris golden pulse",
    cityStory: "Haussmann boulevards lit from below, the Seine reflecting a city that never dims.",
    character: "Elegant golden nocturne",
    pulse: "26 cultural signals",
    videoSrc: "/media/cities/paris.mp4",
    imageSrc: "/media/cities/paris.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(14, 10, 6, 0.20) 0%, rgba(14, 10, 6, 0.44) 42%, rgba(7, 6, 12, 0.90) 100%)",
    colorGrade: "saturate(1.05) contrast(1.10) brightness(0.66)",
    focalPoint: "50% 44%",
    motionStyle: "settle",
    palette: {
      backgroundFrom: "#1A1510",
      backgroundMiddle: "#1E1A14",
      backgroundTo: "#09080C",
      ambientGlow: "#C4A45A",
      accentGlow: "#9B7FFF",
      shadow: "#0C0A0E",
    },
    ambientParticles: { count: 18, speed: 0.12, label: "Boulevard light" },
    mediaDescriptor: "Aerial Paris / golden hour",
  },
  amsterdam: {
    id: "amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    sceneTitle: "Amsterdam canal frequency",
    cityStory: "Canal light reflections doubling the city at night, bridges and neon cutting cold water.",
    character: "Canal reflection nocturne",
    pulse: "22 water signals",
    videoSrc: "/media/cities/amsterdam.mp4",
    imageSrc: "/media/cities/amsterdam.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(5, 9, 16, 0.24) 0%, rgba(5, 10, 18, 0.46) 44%, rgba(4, 7, 14, 0.90) 100%)",
    colorGrade: "saturate(0.88) contrast(1.12) brightness(0.63)",
    focalPoint: "50% 48%",
    motionStyle: "still-water",
    palette: {
      backgroundFrom: "#0A1220",
      backgroundMiddle: "#0E182A",
      backgroundTo: "#060A12",
      ambientGlow: "#6AAEC8",
      accentGlow: "#00D4B4",
      shadow: "#060A14",
    },
    ambientParticles: { count: 14, speed: 0.09, label: "Canal reflections" },
    mediaDescriptor: "Canal aerial / night water",
  },
  lisbon: {
    id: "lisbon",
    city: "Lisbon",
    country: "Portugal",
    sceneTitle: "Lisbon atlantic dusk",
    cityStory: "Terracotta hillsides descending to the Tagus, warm Atlantic light fading into violet.",
    character: "Atlantic warm cinematic",
    pulse: "21 fado signals",
    videoSrc: "/media/cities/lisbon.mp4",
    imageSrc: "/media/cities/lisbon.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(16, 9, 6, 0.20) 0%, rgba(14, 9, 6, 0.42) 42%, rgba(7, 6, 12, 0.88) 100%)",
    colorGrade: "saturate(1.08) contrast(1.10) brightness(0.68)",
    focalPoint: "52% 42%",
    motionStyle: "coastal-drift",
    palette: {
      backgroundFrom: "#1E1410",
      backgroundMiddle: "#221814",
      backgroundTo: "#09080C",
      ambientGlow: "#D4845A",
      accentGlow: "#FF3D7F",
      shadow: "#0C0A0E",
    },
    ambientParticles: { count: 19, speed: 0.14, label: "Atlantic light" },
    mediaDescriptor: "Hillside aerial / Atlantic dusk",
  },
  dublin: {
    id: "dublin",
    city: "Dublin",
    country: "Ireland",
    sceneTitle: "Dublin green pulse",
    cityStory: "Georgian terraces and pub-lit streets under a shifting sky, energy raw and unpretentious.",
    character: "Raw green energy",
    pulse: "18 live signals",
    videoSrc: "/media/cities/dublin.mp4",
    imageSrc: "/media/cities/dublin.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(5, 9, 7, 0.26) 0%, rgba(6, 10, 8, 0.48) 44%, rgba(4, 7, 8, 0.90) 100%)",
    colorGrade: "saturate(0.90) contrast(1.12) brightness(0.62)",
    focalPoint: "50% 44%",
    motionStyle: "sea-breeze",
    palette: {
      backgroundFrom: "#0A120E",
      backgroundMiddle: "#0E1814",
      backgroundTo: "#060C08",
      ambientGlow: "#5A9E78",
      accentGlow: "#C8F000",
      shadow: "#060C0A",
    },
    ambientParticles: { count: 15, speed: 0.13, label: "Street energy" },
    mediaDescriptor: "Georgian aerial / overcast night",
  },
  prague: {
    id: "prague",
    city: "Prague",
    country: "Czech Republic",
    sceneTitle: "Prague dark architecture",
    cityStory: "Gothic spires and cobbled squares sinking into a violet night, layered and cinematic.",
    character: "Gothic cinematic dark",
    pulse: "16 underground signals",
    videoSrc: "/media/cities/prague.mp4",
    imageSrc: "/media/cities/prague.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(7, 5, 12, 0.30) 0%, rgba(8, 6, 14, 0.54) 44%, rgba(5, 4, 10, 0.94) 100%)",
    colorGrade: "saturate(0.75) contrast(1.22) brightness(0.54)",
    focalPoint: "50% 38%",
    motionStyle: "slow-push",
    palette: {
      backgroundFrom: "#0E0A18",
      backgroundMiddle: "#130E22",
      backgroundTo: "#08060E",
      ambientGlow: "#8B6FC8",
      accentGlow: "#C4B5FD",
      shadow: "#08060C",
    },
    ambientParticles: { count: 12, speed: 0.08, label: "Gothic light" },
    mediaDescriptor: "Spire aerial / violet night",
  },
  bologna: {
    id: "bologna",
    city: "Bologna",
    country: "Italy",
    sceneTitle: "Bologna terracotta scene",
    cityStory: "Portico arcades and medieval towers glowing red-brick under a lively Italian night.",
    character: "Red brick warm vivace",
    pulse: "24 cultural signals",
    videoSrc: "/media/cities/bologna.mp4",
    imageSrc: "/media/cities/bologna.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(16, 8, 5, 0.20) 0%, rgba(14, 8, 5, 0.43) 42%, rgba(7, 6, 10, 0.88) 100%)",
    colorGrade: "saturate(1.10) contrast(1.10) brightness(0.67)",
    focalPoint: "50% 40%",
    motionStyle: "settle",
    palette: {
      backgroundFrom: "#1C1210",
      backgroundMiddle: "#201614",
      backgroundTo: "#09080C",
      ambientGlow: "#C86A3A",
      accentGlow: "#FF9A3C",
      shadow: "#0C0A0E",
    },
    ambientParticles: { count: 20, speed: 0.14, label: "Arcade light" },
    mediaDescriptor: "Portico aerial / warm night",
  },
  pag: {
    id: "pag",
    city: "Pag",
    country: "Croatia",
    sceneTitle: "Pag crystal scene",
    cityStory: "A bare limestone island above Adriatic blue, minimal and crystalline under summer stars.",
    character: "Mediterranean minimal crystal",
    pulse: "12 island signals",
    videoSrc: "/media/cities/pag.mp4",
    imageSrc: "/media/cities/pag.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(4, 9, 16, 0.18) 0%, rgba(4, 10, 18, 0.38) 42%, rgba(4, 7, 14, 0.86) 100%)",
    colorGrade: "saturate(1.12) contrast(1.08) brightness(0.72)",
    focalPoint: "50% 52%",
    motionStyle: "still-water",
    palette: {
      backgroundFrom: "#081420",
      backgroundMiddle: "#0C1C2E",
      backgroundTo: "#050C18",
      ambientGlow: "#4AB8D4",
      accentGlow: "#00D4B4",
      shadow: "#060C18",
    },
    ambientParticles: { count: 8, speed: 0.07, label: "Sea light" },
    mediaDescriptor: "Island aerial / Adriatic blue",
  },
  athens: {
    id: "athens",
    city: "Athens",
    country: "Greece",
    sceneTitle: "Athens marble night",
    cityStory: "The Acropolis lit white above a sprawling city grid, ancient geometry meeting modern pulse.",
    character: "Ancient warm stone",
    pulse: "22 scene signals",
    videoSrc: "/media/cities/athens.mp4",
    imageSrc: "/media/cities/athens.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(14, 9, 5, 0.22) 0%, rgba(13, 9, 5, 0.44) 42%, rgba(7, 6, 10, 0.90) 100%)",
    colorGrade: "saturate(1.00) contrast(1.12) brightness(0.65)",
    focalPoint: "50% 36%",
    motionStyle: "settle",
    palette: {
      backgroundFrom: "#1A1410",
      backgroundMiddle: "#1E1814",
      backgroundTo: "#09080C",
      ambientGlow: "#C4A46A",
      accentGlow: "#FF9A3C",
      shadow: "#0C0A0E",
    },
    ambientParticles: { count: 16, speed: 0.11, label: "Marble light" },
    mediaDescriptor: "Acropolis aerial / warm night",
  },
  warsaw: {
    id: "warsaw",
    city: "Warsaw",
    country: "Poland",
    sceneTitle: "Warsaw underground pulse",
    cityStory: "Post-industrial corridors and neon-lit underpasses, a city reinventing itself after dark.",
    character: "Post-industrial underground",
    pulse: "17 raw signals",
    videoSrc: "/media/cities/warsaw.mp4",
    imageSrc: "/media/cities/warsaw.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(5, 6, 10, 0.30) 0%, rgba(6, 7, 12, 0.54) 44%, rgba(4, 5, 9, 0.94) 100%)",
    colorGrade: "saturate(0.62) contrast(1.22) brightness(0.52)",
    focalPoint: "50% 44%",
    motionStyle: "slow-push",
    palette: {
      backgroundFrom: "#0C0E16",
      backgroundMiddle: "#101420",
      backgroundTo: "#07080E",
      ambientGlow: "#7A7EA8",
      accentGlow: "#9B7FFF",
      shadow: "#060710",
    },
    ambientParticles: { count: 10, speed: 0.09, label: "Urban signals" },
    mediaDescriptor: "Industrial aerial / cold night",
  },
  budapest: {
    id: "budapest",
    city: "Budapest",
    country: "Hungary",
    sceneTitle: "Budapest Danube glow",
    cityStory: "The Danube splitting the city in gold, parliament and bridges reflected in slow water.",
    character: "Danube golden elegance",
    pulse: "20 night signals",
    videoSrc: "/media/cities/budapest.mp4",
    imageSrc: "/media/cities/budapest.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(14, 9, 5, 0.20) 0%, rgba(13, 9, 5, 0.44) 42%, rgba(7, 6, 12, 0.88) 100%)",
    colorGrade: "saturate(1.02) contrast(1.12) brightness(0.65)",
    focalPoint: "50% 46%",
    motionStyle: "still-water",
    palette: {
      backgroundFrom: "#181210",
      backgroundMiddle: "#1C1614",
      backgroundTo: "#09080C",
      ambientGlow: "#C89A4A",
      accentGlow: "#FF9A3C",
      shadow: "#0C0A0E",
    },
    ambientParticles: { count: 17, speed: 0.10, label: "River light" },
    mediaDescriptor: "Danube aerial / golden night",
  },
  zagreb: {
    id: "zagreb",
    city: "Zagreb",
    country: "Croatia",
    sceneTitle: "Zagreb alternative scene",
    cityStory: "A compact central European city, alternative venues and brutalist architecture after dark.",
    character: "Central European alternative",
    pulse: "14 underground signals",
    videoSrc: "/media/cities/zagreb.mp4",
    imageSrc: "/media/cities/zagreb.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(7, 6, 12, 0.28) 0%, rgba(8, 6, 14, 0.52) 44%, rgba(5, 5, 10, 0.92) 100%)",
    colorGrade: "saturate(0.72) contrast(1.18) brightness(0.56)",
    focalPoint: "50% 42%",
    motionStyle: "slow-push",
    palette: {
      backgroundFrom: "#0E0C18",
      backgroundMiddle: "#121020",
      backgroundTo: "#08070E",
      ambientGlow: "#7B6AA8",
      accentGlow: "#C4B5FD",
      shadow: "#08060C",
    },
    ambientParticles: { count: 11, speed: 0.09, label: "Venue signals" },
    mediaDescriptor: "Urban aerial / alternative night",
  },
  brussels: {
    id: "brussels",
    city: "Brussels",
    country: "Belgium",
    sceneTitle: "Brussels nocturne",
    cityStory: "Art Nouveau facades and lit-up grand places meeting a northern night, quiet and electric.",
    character: "Northern nocturne electric",
    pulse: "19 scene signals",
    videoSrc: "/media/cities/brussels.mp4",
    imageSrc: "/media/cities/brussels.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(6, 7, 12, 0.26) 0%, rgba(7, 8, 14, 0.50) 44%, rgba(5, 6, 12, 0.92) 100%)",
    colorGrade: "saturate(0.80) contrast(1.14) brightness(0.60)",
    focalPoint: "50% 42%",
    motionStyle: "settle",
    palette: {
      backgroundFrom: "#0C0E18",
      backgroundMiddle: "#101422",
      backgroundTo: "#070810",
      ambientGlow: "#8A90C8",
      accentGlow: "#9B7FFF",
      shadow: "#07080E",
    },
    ambientParticles: { count: 13, speed: 0.10, label: "Grand place light" },
    mediaDescriptor: "Art Nouveau aerial / night",
  },
  vienna: {
    id: "vienna",
    city: "Vienna",
    country: "Austria",
    sceneTitle: "Vienna imperial night",
    cityStory: "Ring boulevard palaces lit amber, a city where classical architecture breathes after dark.",
    character: "Imperial golden classical",
    pulse: "23 cultural signals",
    videoSrc: "/media/cities/vienna.mp4",
    imageSrc: "/media/cities/vienna.jpg",
    overlayGradient: "linear-gradient(180deg, rgba(14, 10, 5, 0.22) 0%, rgba(14, 10, 5, 0.44) 42%, rgba(7, 6, 12, 0.90) 100%)",
    colorGrade: "saturate(0.98) contrast(1.10) brightness(0.64)",
    focalPoint: "50% 40%",
    motionStyle: "settle",
    palette: {
      backgroundFrom: "#1A1410",
      backgroundMiddle: "#1E1814",
      backgroundTo: "#09080C",
      ambientGlow: "#C4A84A",
      accentGlow: "#9B7FFF",
      shadow: "#0C0A0E",
    },
    ambientParticles: { count: 16, speed: 0.11, label: "Palace light" },
    mediaDescriptor: "Ring boulevard aerial / imperial night",
  },
};

export const CITY_ORDER: CityId[] = [
  "rome",
  "barcelona",
  "berlin",
  "copenhagen",
  "bari",
  "london",
  "paris",
  "amsterdam",
  "lisbon",
  "dublin",
  "prague",
  "bologna",
  "pag",
  "athens",
  "warsaw",
  "budapest",
  "zagreb",
  "brussels",
  "vienna",
  "default",
];
